# # # Welcome to Serverless!
# service: coreceptionist-serverless
# app: product-api

# provider:
#   name: aws
#   runtime: nodejs14.x
#   stage: dev
#   region: us-west-2

# functions:
#   server:
#     handler: app.handler
#     events:
#       - http:
#           path: /
#           method: get
#       - http:
#           path: /{proxy+}
#           method: ANY
#           cors: true

# plugins:
#   - serverless-offline
#   - serverless-dotenv-plugin
service: coreceptionist-serverless
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-west-2
functions:
  app:
    handler: app.handler # reference the file and exported method
    events: # events trigger lambda functions
      - http: # this is an API Gateway HTTP event trigger
          path: /
          method: GET
          cors: true
      - http: # all routes get proxied to the Express router
          path: /{proxy+}
          method: ANY
          cors: true
plugins:
  - serverless-offline
  - serverless-dotenv-plugin
